### ISSUE TITLE
beautify prototype box

### ISSUE THREAD

**Issue by wilzbach** [adamdruppe/adrdox#9] opened 2016-05-12 14:07 UTC
![image](https://cloud.githubusercontent.com/assets/4370550/15217240/46914624-1863-11e6-8b6b-ab1091c68d1f.png)

There's still a lot of visual potential, e.g 
- why is there so much space
- having the brackets open for one parameter seems a bit weird

http://dpldocs.info/experimental-docs/std.ascii.isAlphaNum.html

**Comment by adamdruppe** [comment] 2018-02-20 15:56
Space is a good thing for legibility. In simple functions, it doesn't help but also doesn't hurt, and in complex functions, it is an enormous help. Do an A/B test with my docs and dlang.org with someone. My layout wins hands-down in ever test except the trivial where it doesn't matter anyway..

Does that mean it is perfect? No, but a request to improve/beautify it must

1. be specific

and

2. pass a user acceptance A/B test, where less-experienced users are able to quickly find the information they want. A purely aesthetic improvement is ok but only if there's no significant hit on this. Packing text usually hurts with quickly scanning (remember, users rarely *read* docs, they skim them for what they want at the time).


I hear the criticism that the `Params:` section and the prototype duplicate some info but there's a separate issue open for that so I'll talk about it there.

I'm gonna close this as "not a bug".

**Closed by adamdruppe** 2018-02-20 15:56 UTC
